repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.8 
    hooks:
      # CHỈ tự động chạy ruff format để căn lề, chỉnh dấu ngoặc, dấu nháy.
      # Tuyệt đối không xóa biến, không can thiệp logic code.
      - id: ruff-format